# Generated by Django 4.2 on 2026-08-18 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=2, help_text='Internal length in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.DecimalField(decimal_places=2, help_text='Internal width in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.DecimalField(decimal_places=2, help_text='Internal height in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost per box', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of this product in the order', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shipping.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
